<a href="https://colab.research.google.com/github/Cafeko/Projeto_integra-o-BD-2026.1/blob/anysabele/ELT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Projeto de Integração de Dados – SAMP (ANEEL)
 Implementação do Pipeline ELT utilizando PostgreSQL e dbt

## Objetivo

Este notebook apresenta a implementação do processo ELT (Extract, Load and Transform) utilizando PostgreSQL e dbt.

Os dados foram carregados inicialmente para uma camada Bronze, transformados em uma camada Silver e posteriormente organizados em um Data Warehouse modelado em Esquema Estrela (camada Gold).

## Configuração do Ambiente

Nesta etapa são instaladas e configuradas as ferramentas necessárias para execução do pipeline ELT:

- PostgreSQL
- SQLAlchemy
- Psycopg2
- Pandas

In [75]:
!apt-get update -qq
!apt-get install -y postgresql postgresql-contrib

W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
postgresql is already the newest version (14+238).
postgresql-contrib is already the newest version (14+238).
0 upgraded, 0 newly installed, 0 to remove and 16 not upgraded.

In [76]:
!service postgresql start

 * Starting PostgreSQL 14 database server
   ...done.

In [77]:
!sudo -u postgres psql -c "ALTER USER postgres PASSWORD 'postgres';"

ALTER ROLE

In [78]:
!sudo -u postgres createdb samp

createdb: error: database creation failed: ERROR:  database "samp" already exists

In [79]:
!pip install sqlalchemy psycopg2-binary

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.49)
Requirement already satisfied: psycopg2-binary in /usr/local/lib/python3.12/dist-packages (2.9.12)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.5.1)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)

In [80]:
from sqlalchemy import create_engine

In [81]:
engine = create_engine(
    "postgresql://postgres:postgres@localhost:5432/samp"
)

In [82]:
import pandas as pd

## Camada Bronze

Os arquivos consolidados do SAMP foram carregados para o PostgreSQL sem transformações significativas.

Esta camada preserva os dados originais e serve como ponto de partida para as etapas posteriores do processo ELT.

In [83]:
bronze_df = pd.read_csv("bronze_dataset.csv")

bronze_df.to_sql(
    "bronze_samp",
    engine,
    if_exists="replace",
    index=False
)

329

Vizualizar número de linhas, explorar colunas e tipo de arquivo

In [84]:
pd.read_sql(
    "SELECT COUNT(*) FROM bronze_samp",
    engine
)

     count
0  3029329

In [85]:
pd.read_sql("""
SELECT *
FROM bronze_samp
LIMIT 2
""", engine)

,DatGeracaoConjuntoDados,NumCNPJAgenteDistribuidora,SigAgenteDistribuidora,NomAgenteDistribuidora,NomTipoMercado,DscModalidadeTarifaria,DscSubGrupoTarifario,DscClasseConsumoMercado,DscSubClasseConsumidor,DscDetalheConsumidor,IdeAgenteAcessante,NumCNPJAgenteAcessante,NomAgenteAcessante,DscPostoTarifario,DscOpcaoEnergia,DscDetalheMercado,DatCompetencia,VlrMercado,arquivo_origem
0,2026-05-15,4065033000170,EAC,ENERGISA ACRE - DISTRIBUIDORA DE ENERGIA S.A,Sistema Isolado - Regular,Convencional,B1,Residencial,Residencial baixa renda – faixa 04,Não se aplica,None,3.712167e+10,Não se aplica,Não se aplica,CATIVO,Energia TE (kWh),2024-01-01,583151.00,samp-2024.csv
1,2026-05-15,4065033000170,EAC,ENERGISA ACRE - DISTRIBUIDORA DE ENERGIA S.A,Regular,Convencional,B1,Residencial,Residencial baixa renda – faixa 01,Não se aplica,None,3.712167e+10,Não se aplica,Não se aplica,CATIVO,PIS/PASEP (R$),2024-01-01,5431.29,samp-2024.csv

In [86]:
pd.read_sql("""
SELECT column_name, data_type
FROM information_schema.columns
WHERE table_name = 'bronze_samp'
""", engine)

                   column_name         data_type
0   NumCNPJAgenteDistribuidora            bigint
1           IdeAgenteAcessante  double precision
2                   VlrMercado  double precision
3       NumCNPJAgenteAcessante  double precision
4       DscModalidadeTarifaria              text
5         DscSubGrupoTarifario              text
6      DscClasseConsumoMercado              text
7       DscSubClasseConsumidor              text
8         DscDetalheConsumidor              text
9           NomAgenteAcessante              text
10           DscPostoTarifario              text
11             DscOpcaoEnergia              text
12           DscDetalheMercado              text
13              DatCompetencia              text
14     DatGeracaoConjuntoDados              text
15              arquivo_origem              text
16      SigAgenteDistribuidora              text
17      NomAgenteDistribuidora              text
18              NomTipoMercado              text

## Configuração do dbt

O dbt foi utilizado para implementar as transformações diretamente no PostgreSQL, caracterizando a abordagem ELT.

As transformações são definidas como modelos SQL versionados e executados pelo dbt.

In [87]:
!pip install dbt-core==1.9.4 dbt-postgres==1.9.0

Requirement already satisfied: dbt-core==1.9.4 in /usr/local/lib/python3.12/dist-packages (1.9.4)
Requirement already satisfied: dbt-postgres==1.9.0 in /usr/local/lib/python3.12/dist-packages (1.9.0)
Requirement already satisfied: agate<1.10,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from dbt-core==1.9.4) (1.9.1)
Requirement already satisfied: Jinja2<4,>=3.1.3 in /usr/local/lib/python3.12/dist-packages (from dbt-core==1.9.4) (3.1.6)
Requirement already satisfied: mashumaro<3.15,>=3.9 in /usr/local/lib/python3.12/dist-packages (from mashumaro[msgpack]<3.15,>=3.9->dbt-core==1.9.4) (3.14)
Requirement already satisfied: click<9.0,>=8.0.2 in /usr/local/lib/python3.12/dist-packages (from dbt-core==1.9.4) (8.4.0)
Requirement already satisfied: networkx<4.0,>=2.3 in /usr/local/lib/python3.12/dist-packages (from dbt-core==1.9.4) (3.6.1)
Requirement already satisfied: protobuf<6.0,>=5.0 in /usr/local/lib/python3.12/dist-packages (from dbt-core==1.9.4) (5.29.6)
Requirement already satisfied: requests<3.0.0 in /usr/local/lib/python3.12/dist-packages (from dbt-core==1.9.4) (2.32.4)
Requirement already satisfied: snowplow-tracker<2.0,>=1.0.2 in /usr/local/lib/python3.12/dist-packages (from dbt-core==1.9.4) (1.1.0)
Requirement already satisfied: pathspec<0.13,>=0.9 in /usr/local/lib/python3.12/dist-packages (from dbt-core==1.9.4) (0.12.1)
Requirement already satisfied: sqlparse<0.6.0,>=0.5.0 in /usr/local/lib/python3.12/dist-packages (from dbt-core==1.9.4) (0.5.5)
Requirement already satisfied: dbt-extractor<=0.6,>=0.5.0 in /usr/local/lib/python3.12/dist-packages (from dbt-core==1.9.4) (0.6.0)
Requirement already satisfied: dbt-semantic-interfaces<0.8,>=0.7.4 in /usr/local/lib/python3.12/dist-packages (from dbt-core==1.9.4) (0.7.5)
Requirement already satisfied: dbt-common<2.0,>=1.13.0 in /usr/local/lib/python3.12/dist-packages (from dbt-core==1.9.4) (1.27.1)
Requirement already satisfied: dbt-adapters<2.0,>=1.10.1 in /usr/local/lib/python3.12/dist-packages (from dbt-core==1.9.4) (1.16.3)
Requirement already satisfied: packaging>20.9 in /usr/local/lib/python3.12/dist-packages (from dbt-core==1.9.4) (26.2)
Requirement already satisfied: pytz>=2015.7 in /usr/local/lib/python3.12/dist-packages (from dbt-core==1.9.4) (2025.2)
Requirement already satisfied: pyyaml>=6.0 in /usr/local/lib/python3.12/dist-packages (from dbt-core==1.9.4) (6.0.3)
Requirement already satisfied: daff>=1.3.46 in /usr/local/lib/python3.12/dist-packages (from dbt-core==1.9.4) (1.4.2)
Requirement already satisfied: typing-extensions>=4.4 in /usr/local/lib/python3.12/dist-packages (from dbt-core==1.9.4) (4.15.0)
Requirement already satisfied: psycopg2-binary<3.0,>=2.9 in /usr/local/lib/python3.12/dist-packages (from dbt-postgres==1.9.0) (2.9.12)
Requirement already satisfied: Babel>=2.0 in /usr/local/lib/python3.12/dist-packages (from agate<1.10,>=1.7.0->dbt-core==1.9.4) (2.18.0)
Requirement already satisfied: isodate>=0.5.4 in /usr/local/lib/python3.12/dist-packages (from agate<1.10,>=1.7.0->dbt-core==1.9.4) (0.6.1)
Requirement already satisfied: leather>=0.3.2 in /usr/local/lib/python3.12/dist-packages (from agate<1.10,>=1.7.0->dbt-core==1.9.4) (0.4.1)
Requirement already satisfied: parsedatetime!=2.5,>=2.1 in /usr/local/lib/python3.12/dist-packages (from agate<1.10,>=1.7.0->dbt-core==1.9.4) (2.6)
Requirement already satisfied: python-slugify>=1.2.1 in /usr/local/lib/python3.12/dist-packages (from agate<1.10,>=1.7.0->dbt-core==1.9.4) (8.0.4)
Requirement already satisfied: pytimeparse>=1.1.5 in /usr/local/lib/python3.12/dist-packages (from agate<1.10,>=1.7.0->dbt-core==1.9.4) (1.1.8)
Requirement already satisfied: dbt-protos<2.0,>=1.0.291 in /usr/local/lib/python3.12/dist-packages (from dbt-adapters<2.0,>=1.10.1->dbt-core==1.9.4) (1.0.514)
Requirement already satisfied: colorama<0.5,>=0.3.9 in /usr/local/lib/python3.12/dist-packages (from dbt-common<2.0,>=1.13.0->dbt-core==1.9.4) (0.4.6)
Requirement already satisfied: deepdiff<8.0,>=7.0 in /usr/local/lib/python3.12/dist-packages (from dbt-common<2.0,>=1.13.0->dbt-core==1.9.4) (7.0.1)
Requirement already satisfied: jsonschema<5.0,>=4.0 in /usr/local/lib/python3.12/dist-packages (from dbt-common<2.0,>=1.13.0->dbt-core==1.9.4) (4.26.0)
Requirement already satisfied: python-dateutil<3.0,>=2.0 in /usr/local/lib/python3.12/dist-packages (from dbt-common<2.0,>=1.13.0->dbt-core==1.9.4) (2.9.0.post0)
Requirement already satisfied: importlib-metadata<9,>=6.0 in /usr/local/lib/python3.12/dist-packages (from dbt-semantic-interfaces<0.8,>=0.7.4->dbt-core==1.9.4) (8.7.1)
Requirement already satisfied: more-itertools<11.0,>=8.0 in /usr/local/lib/python3.12/dist-packages (from dbt-semantic-interfaces<0.8,>=0.7.4->dbt-core==1.9.4) (10.8.0)
Requirement already satisfied: pydantic<3,>=1.10 in /usr/local/lib/python3.12/dist-packages (from dbt-semantic-interfaces<0.8,>=0.7.4->dbt-core==1.9.4) (2.12.3)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from Jinja2<4,>=3.1.3->dbt-core==1.9.4) (3.0.3)
Requirement already satisfied: msgpack>=0.5.6 in /usr/local/lib/python3.12/dist-packages (from mashumaro[msgpack]<3.15,>=3.9->dbt-core==1.9.4) (1.1.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0->dbt-core==1.9.4) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0->dbt-core==1.9.4) (3.15)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0->dbt-core==1.9.4) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0->dbt-core==1.9.4) (2026.5.20)
Requirement already satisfied: ordered-set<4.2.0,>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from deepdiff<8.0,>=7.0->dbt-common<2.0,>=1.13.0->dbt-core==1.9.4) (4.1.0)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.12/dist-packages (from importlib-metadata<9,>=6.0->dbt-semantic-interfaces<0.8,>=0.7.4->dbt-core==1.9.4) (4.1.0)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from isodate>=0.5.4->agate<1.10,>=1.7.0->dbt-core==1.9.4) (1.17.0)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema<5.0,>=4.0->dbt-common<2.0,>=1.13.0->dbt-core==1.9.4) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema<5.0,>=4.0->dbt-common<2.0,>=1.13.0->dbt-core==1.9.4) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema<5.0,>=4.0->dbt-common<2.0,>=1.13.0->dbt-core==1.9.4) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema<5.0,>=4.0->dbt-common<2.0,>=1.13.0->dbt-core==1.9.4) (0.30.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.10->dbt-semantic-interfaces<0.8,>=0.7.4->dbt-core==1.9.4) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.10->dbt-semantic-interfaces<0.8,>=0.7.4->dbt-core==1.9.4) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.10->dbt-semantic-interfaces<0.8,>=0.7.4->dbt-core==1.9.4) (0.4.2)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.12/dist-packages (from python-slugify>=1.2.1->agate<1.10,>=1.7.0->dbt-core==1.9.4) (1.3)

In [88]:
!mkdir -p ~/.dbt

In [89]:
!mkdir -p samp_dbt/models/silver
!mkdir -p samp_dbt/models/gold

In [90]:
# @title
%%writefile samp_dbt/models/sources.yml
version: 2

sources:
  - name: bronze
    schema: public
    tables:
      - name: bronze_samp

Overwriting samp_dbt/models/sources.yml

In [91]:
# @title
%%writefile samp_dbt/dbt_project.yml
name: 'samp_dbt'
version: '1.0'
config-version: 2

profile: 'samp_dbt'

model-paths: ["models"]

models:
  samp_dbt:
    silver:
      +materialized: table
    gold:
      +materialized: table

Overwriting samp_dbt/dbt_project.yml

In [92]:
# @title
%%writefile ~/.dbt/profiles.yml
samp_dbt:
  target: dev

  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: postgres
      port: 5432
      dbname: samp
      schema: public
      threads: 1

Overwriting /root/.dbt/profiles.yml

#Construção da Camada Silver

Nesta etapa foram realizadas transformações de limpeza e padronização dos dados.

In [110]:
%%writefile samp_dbt/models/silver/silver_samp.sql
SELECT DISTINCT
    CAST("DatCompetencia" AS DATE) AS dat_competencia,
    CAST("DatGeracaoConjuntoDados" AS DATE) AS dat_geracao,

    "NumCNPJAgenteDistribuidora" AS cnpj_distribuidora,
    "SigAgenteDistribuidora" AS sigla_distribuidora,
    "NomAgenteDistribuidora" AS nome_distribuidora,

    COALESCE("NumCNPJAgenteAcessante", 0) AS cnpj_acessante,
    COALESCE("IdeAgenteAcessante", 0) AS id_acessante,
    COALESCE("NomAgenteAcessante", 'Nao Informado') AS nome_acessante,

    "NomTipoMercado",
    "DscModalidadeTarifaria",
    "DscSubGrupoTarifario",
    "DscClasseConsumoMercado",
    "DscSubClasseConsumidor",
    "DscDetalheConsumidor",
    "DscPostoTarifario",
    "DscOpcaoEnergia",
    "DscDetalheMercado",

    "VlrMercado",
    "arquivo_origem"

FROM {{ source('bronze', 'bronze_samp') }}

WHERE "DatCompetencia" IS NOT NULL
  AND "VlrMercado" IS NOT NULL

Overwriting samp_dbt/models/silver/silver_samp.sql

Visualizar

In [112]:
pd.read_sql("""
SELECT COUNT(*)
FROM silver_samp
""", engine)

     count
0  3029186

In [113]:
pd.read_sql("""
SELECT *
FROM silver_samp
LIMIT 2
""", engine)

,dat_competencia,dat_geracao,cnpj_distribuidora,sigla_distribuidora,nome_distribuidora,cnpj_acessante,id_acessante,nome_acessante,NomTipoMercado,DscModalidadeTarifaria,DscSubGrupoTarifario,DscClasseConsumoMercado,DscSubClasseConsumidor,DscDetalheConsumidor,DscPostoTarifario,DscOpcaoEnergia,DscDetalheMercado,VlrMercado,arquivo_origem
0,2024-01-01,2026-05-15,1229747000189,CERGAPA,COOPERATIVA DE ELETRICIDADE GRÃO PARÁ,0.0,0.0,Não se aplica,Regular,Verde,A4,Industrial,Não se aplica,Fonte incentivada,Fora ponta,LIVRE,Energia TUSD (kWh),445817.00,samp-2024.csv
1,2024-01-01,2026-05-15,1229747000189,CERGAPA,COOPERATIVA DE ELETRICIDADE GRÃO PARÁ,0.0,0.0,Não se aplica,Regular,Verde,A4,Industrial,Não se aplica,Fonte incentivada,Fora ponta,LIVRE,Receita Energia (R$),43097.13,samp-2024.csv

## 5. Construção da Camada Gold (Data Warehouse)

A camada Gold corresponde ao Data Warehouse modelado em Esquema Estrela.

Foram criadas dimensões para representar os principais elementos analíticos do domínio e uma tabela fato para armazenar as métricas de mercado.

In [114]:
%%writefile samp_dbt/models/gold/dim_tempo.sql
SELECT DISTINCT

    ROW_NUMBER() OVER (
        ORDER BY dat_competencia
    ) AS tempo_id,

    dat_competencia,

    EXTRACT(YEAR FROM dat_competencia) AS ano,
    EXTRACT(MONTH FROM dat_competencia) AS mes,
    EXTRACT(QUARTER FROM dat_competencia) AS trimestre

FROM {{ ref('silver_samp') }}

Overwriting samp_dbt/models/gold/dim_tempo.sql

In [115]:
%%writefile samp_dbt/models/gold/dim_distribuidora.sql
SELECT DISTINCT

    ROW_NUMBER() OVER (
        ORDER BY cnpj_distribuidora
    ) AS distribuidora_id,

    cnpj_distribuidora,
    sigla_distribuidora,
    nome_distribuidora

FROM {{ ref('silver_samp') }}

Overwriting samp_dbt/models/gold/dim_distribuidora.sql

In [116]:
%%writefile samp_dbt/models/gold/dim_acessante.sql
SELECT DISTINCT

    ROW_NUMBER() OVER (
        ORDER BY cnpj_acessante
    ) AS acessante_id,

    cnpj_acessante,
    id_acessante,
    nome_acessante

FROM {{ ref('silver_samp') }}

Overwriting samp_dbt/models/gold/dim_acessante.sql

In [117]:
%%writefile samp_dbt/models/gold/dim_mercado.sql
SELECT DISTINCT

    ROW_NUMBER() OVER (
        ORDER BY
            "NomTipoMercado",
            "DscClasseConsumoMercado"
    ) AS mercado_id,

    "NomTipoMercado",
    "DscModalidadeTarifaria",
    "DscSubGrupoTarifario",
    "DscClasseConsumoMercado",
    "DscSubClasseConsumidor",
    "DscDetalheConsumidor",
    "DscPostoTarifario",
    "DscOpcaoEnergia",
    "DscDetalheMercado"

FROM {{ ref('silver_samp') }}

Overwriting samp_dbt/models/gold/dim_mercado.sql

Visualizar

In [120]:
pd.read_sql("""
SELECT *
FROM dim_tempo
LIMIT 5
""", engine)

   tempo_id dat_competencia     ano  mes  trimestre
0     14445      2024-01-01  2024.0  1.0        1.0
1     24873      2024-01-01  2024.0  1.0        1.0
2     16277      2024-01-01  2024.0  1.0        1.0
3      4776      2024-01-01  2024.0  1.0        1.0
4     25387      2024-01-01  2024.0  1.0        1.0

In [121]:
pd.read_sql("""
SELECT *
FROM dim_distribuidora
LIMIT 5
""", engine)

,distribuidora_id,cnpj_distribuidora,sigla_distribuidora,nome_distribuidora
0,11003,1377555000110,CHESP,COMPANHIA HIDROELETRICA SAO PATRICIO - CHESP
1,5873,1229747000189,CERGAPA,COOPERATIVA DE ELETRICIDADE GRÃO PARÁ
2,2914,1229747000189,CERGAPA,COOPERATIVA DE ELETRICIDADE GRÃO PARÁ
3,9937,1377555000110,CHESP,COMPANHIA HIDROELETRICA SAO PATRICIO - CHESP
4,15070,1377555000110,CHESP,COMPANHIA HIDROELETRICA SAO PATRICIO - CHESP

In [122]:
pd.read_sql("""
SELECT *
FROM dim_acessante
LIMIT 5
""", engine)

   acessante_id  cnpj_acessante  id_acessante nome_acessante
0         25680             0.0           0.0      Dacolonia
1         23120             0.0           0.0   GD (GRUPO A)
2         15966             0.0           0.0  Não se aplica
3         23995             0.0           0.0    São João PA
4         10786             0.0           0.0      Luiz Dias

In [123]:
pd.read_sql("""
SELECT *
FROM dim_mercado
LIMIT 5
""", engine)

,mercado_id,NomTipoMercado,DscModalidadeTarifaria,DscSubGrupoTarifario,DscClasseConsumoMercado,DscSubClasseConsumidor,DscDetalheConsumidor,DscPostoTarifario,DscOpcaoEnergia,DscDetalheMercado
0,1,Refaturamento - Regular,Convencional,B3,Comercial,Não se aplica,Não se aplica,Não se aplica,CATIVO,PIS/PASEP (R$)
1,2,Refaturamento - Regular,Convencional,B3,Comercial,Não se aplica,Não se aplica,Não se aplica,CATIVO,Receita Bandeiras (R$)
2,3,Refaturamento - Regular,Convencional,B3,Comercial,Não se aplica,Não se aplica,Não se aplica,CATIVO,Receita Energia (R$)
3,4,Refaturamento - Regular,Verde,A4,Comercial,Não se aplica,Não se aplica,Ponta,CATIVO,Receita Energia (R$)
4,5,Refaturamento - Regular,Convencional,B3,Comercial,Não se aplica,Não se aplica,Não se aplica,CATIVO,COFINS (R$)

## 6. Criação da Tabela Fato

A tabela fato concentra as métricas de negócio associadas às dimensões do modelo.

A métrica principal armazenada é o valor de mercado (VlrMercado).

In [124]:
%%writefile samp_dbt/models/gold/fato_mercado.sql
SELECT

    ROW_NUMBER() OVER () AS fato_id,

    dat_competencia,

    cnpj_distribuidora,

    cnpj_acessante,

    "NomTipoMercado",

    "VlrMercado"

FROM {{ ref('silver_samp') }}

Overwriting samp_dbt/models/gold/fato_mercado.sql

In [126]:
!cd samp_dbt && dbt run

21:50:24  Running with dbt=1.9.4
21:50:25  Registered adapter: postgres=1.9.0
21:50:26  Found 8 models, 4 data tests, 1 source, 434 macros
21:50:26
21:50:26  Concurrency: 1 threads (target='dev')
21:50:26
21:50:26  1 of 8 START sql table model public.my_first_dbt_model ......................... [RUN]
21:50:26  1 of 8 OK created sql table model public.my_first_dbt_model .................... [SELECT 2 in 0.18s]
21:50:26  2 of 8 START sql table model public.silver_samp ................................ [RUN]
21:51:54  2 of 8 OK created sql table model public.silver_samp ........................... [SELECT 3029186 in 88.02s]
21:51:54  3 of 8 START sql view model public.my_second_dbt_model ......................... [RUN]
21:51:54  3 of 8 OK created sql view model public.my_second_dbt_model .................... [CREATE VIEW in 0.10s]
21:51:54  4 of 8 START sql table model public.dim_acessante .............................. [RUN]
21:52:27  4 of 8 OK created sql table model public.dim_acessante ......................... [SELECT 3029186 in 33.05s]
21:52:27  5 of 8 START sql table model public.dim_distribuidora .......................... [RUN]
21:52:58  5 of 8 OK created sql table model public.dim_distribuidora ..................... [SELECT 3029186 in 30.47s]
21:52:58  6 of 8 START sql table model public.dim_mercado ................................ [RUN]
21:53:36  6 of 8 OK created sql table model public.dim_mercado ........................... [SELECT 3029186 in 37.92s]
21:53:36  7 of 8 START sql table model public.dim_tempo .................................. [RUN]
21:53:59  7 of 8 OK created sql table model public.dim_tempo ............................. [SELECT 3029186 in 23.72s]
21:53:59  8 of 8 START sql table model public.fato_mercado ............................... [RUN]
21:54:07  8 of 8 OK created sql table model public.fato_mercado .......................... [SELECT 3029186 in 7.60s]
21:54:07
21:54:07  Finished running 7 table models, 1 view model in 0 hours 3 minutes and 41.37 seconds (221.37s).
21:54:07
21:54:07  Completed successfully
21:54:07
21:54:07  Done. PASS=8 WARN=0 ERROR=0 SKIP=0 TOTAL=8

Visualizar

In [125]:
pd.read_sql("""
SELECT *
FROM fato_mercado
LIMIT 5
""", engine)

,fato_id,dat_competencia,cnpj_distribuidora,cnpj_acessante,NomTipoMercado,VlrMercado
0,1,2024-01-01,1229747000189,0.0,Regular,445817.000000
1,2,2024-01-01,1229747000189,0.0,Regular,43097.130000
2,3,2024-01-01,1229747000189,0.0,Regular,1158.000000
3,4,2024-01-01,1229747000189,0.0,Regular,49.921533
4,5,2024-01-01,1229747000189,0.0,Regular,48332.340000